config/routes.rb
AppsContest::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :promotions
  resources :categories
  resources :stores
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root "maps#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :promotions, dependent: :destroy
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :check_logged_in?, only: [:new, :edit, :update, :destroy]
  before_action :check_store_owner, only: [:edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = current_user.stores.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = current_user.stores.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    #redirect if current_user don't own this store
    def check_store_owner
      redirect_to root_path unless current_user.own_store? @store
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :phone_number, :working_hours, :homepage, :description, :note, :pos_x, :pos_y)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<hr>
<input id="begin_pos_x" type="hidden" value="<%= @store.pos_x || 21.005358985589186%>">
<input id="begin_pos_y" type="hidden" value="<%= @store.pos_y || 105.83716351318367%>">
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="top-board">
    <div class="basic-info">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :address %><br>
        <%= f.text_field :address %>
      </div>
      <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number %>
      </div>
      <div class="field">
        <%= f.label :working_hours %><br>
        <%= f.text_field :working_hours %>
      </div>  
      <div class="field">
        <%= f.label :homepage %><br>
        <%= f.text_field :homepage %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
    </div>
    
    <div class="map-area">
      <b>Drag the marker to your store's location!</b>
      <div id="mapCanvas"></div>
      <div class="field hide">
        <%= f.label :pos_x %><br>
        <%= f.text_field :pos_x, id: "pos_x", readonly: true %>
      </div>
      <div class="field hide">
        <%= f.label :pos_y %><br>
        <%= f.text_field :pos_y, id: "pos_y", readonly: true %>
      </div>
      <div id="infoPanel">
        <b>Closest matching address:</b>
        <div id="address"></div>
      </div>
    </div>
  </div>
  <hr>
  <div class="detail-info">
    <span>Edit your introduce article:</span>
    <%= f.cktext_area :note, :class => "", :ckeditor => {:language => "en",:uiColor => "#8d8d8d", :toolbar => "mini", :height => 500} %>  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<style>
  #mapCanvas {
    width: 100%;
    height: 400px;
  }
</style>
<script type="text/javascript">
  var geocoder = new google.maps.Geocoder();

  function geocodePosition(pos) {
    geocoder.geocode({
      latLng: pos
    }, function(responses) {
      if (responses && responses.length > 0) {
        updateMarkerAddress(responses[0].formatted_address);
      } else {
        updateMarkerAddress('Cannot determine address at this location.');
      }
    });
  }

  function updateMarkerPosition(latLng) {
    $("#pos_x").val(latLng.lat());
    $("#pos_y").val(latLng.lng());
  }

  function updateMarkerAddress(str) {
    document.getElementById('address').innerHTML = str;
  }

  function initialize() {
    begin_pos_x = $("#begin_pos_x").val();
    begin_pos_y = $("#begin_pos_y").val();
    var latLng = new google.maps.LatLng(begin_pos_x, begin_pos_y);
    var map = new google.maps.Map(document.getElementById('mapCanvas'), {
      zoom: 13,
      center: latLng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    var marker = new google.maps.Marker({
      position: latLng,
      title: 'Point A',
      map: map,
      draggable: true
    });
    
    // Update current position info.
    updateMarkerPosition(latLng);
    geocodePosition(latLng);
    
    google.maps.event.addListener(marker, 'drag', function() {
      updateMarkerPosition(marker.getPosition());
    });
    
    google.maps.event.addListener(marker, 'dragend', function() {
      geocodePosition(marker.getPosition());
    });
  }

  // Onload handler to fire off the app.
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Note</th>
      <th>Pos x</th>
      <th>Pos y</th>
      <th>User ID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= store.description %></td>
        <td><%= store.note %></td>
        <td><%= store.pos_x %></td>
        <td><%= store.pos_y %></td>
        <td><%= store.user_id %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>
<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<div class="wrap">
  <div id="nav">
    <ul id="nav-menu">
      <li class="active"><a href="#">Store</a></li>
      <li><a href="#">Promotion</a></li>
      <li><a href="#">FAQ</a></li>
    </ul>
    <ul class="user-action">
      <li class="active"><a href="#"><img src="/images/like.png">Liked</a></li>
      <li class="active"><a href="#"><img src="/images/follow.png">Following</a></li>
      <li><a href="#"><img src="/images/report.png">Report</a></li>
    </ul>
  </div>
  <div id="search">
    <input type="text" class="search-box" placeholder="Search for something here...">
    <div class="category-select">
      <select>
            <option>Select an option</option>
            <option>Am thuc</option>
            <option>Dien May</option>
            <option>Via He</option>
            <option>Gia dung</option>
        </select>
    </div>  
      <div class="share-button">
        <a href="#" 
        onclick="
          window.open(
            'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
            'facebook-share-dialog', 
            'width=626,height=436'); 
          return false;">

          <img src="/images/facebook_share.png" style="vertical-align:middle; height:45px;">
      </a>
      </div>
  </div>
  <div id="feature">
    <div id="slide-image">
      <img src="http://tapchimonngon.com/images/stories/untitled-2-2.jpg" style="height:100%">
    </div>
    <div id="store-info">
      <h2><%= @store.name %></h2>
      <ul>
        <li><img src="/images/location.png"><%= @store.address %></li>
        <li><img src="/images/phone.png"><%= @store.phone_number %></li>
        <li><img src="/images/working-hours.png"><%= @store.working_hours %></li>
        <li><img src="/images/homepage.png"><a href="#"><%= @store.homepage %></a></li>
      </ul>
      <p><%= @store.description %></p>
    </div>
  </div>
  <div id="container">
    <div id="main">
      <h2 class="slogan">Introduction</h2>
      <div id="content" class="des-info">
        <%= raw @store.note%>
      </div>
      <div class="facebook"  style="margin:auto; width:580px;">
        <div class="fb-comments" data-href="http://www.place.vn/dia-diem/nha-hang-sen-nam-thanh-85" data-width="580"></div>
      </div>
    </div>
    <div id="side-bar">
      <div id="small-map">
        <!-- insert &amp;iwloc=near at end of src attributes in ifram to remove info window-->
        <iframe width="300" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=vi&amp;geocode=&amp;q=B%C3%A1ch+Khoa,+H%C3%A0+N%E1%BB%99i,+Vi%E1%BB%87t+Nam&amp;aq=0&amp;oq=bach+khoa&amp;sll=20.99557,105.848293&amp;sspn=0.022717,0.042272&amp;ie=UTF8&amp;hq=&amp;hnear=B%C3%A1ch+Khoa,+Hai+B%C3%A0+Tr%C6%B0ng,+H%C3%A0+N%E1%BB%99i,+Vi%E1%BB%87t+Nam&amp;t=m&amp;ll=21.002792,105.847692&amp;spn=0.024039,0.025663&amp;z=14&amp;output=embed&amp;iwloc=near"></iframe><br />

        <small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=vi&amp;geocode=&amp;q=B%C3%A1ch+Khoa,+H%C3%A0+N%E1%BB%99i,+Vi%E1%BB%87t+Nam&amp;aq=0&amp;oq=bach+khoa&amp;sll=20.99557,105.848293&amp;sspn=0.022717,0.042272&amp;ie=UTF8&amp;hq=&amp;hnear=B%C3%A1ch+Khoa,+Hai+B%C3%A0+Tr%C6%B0ng,+H%C3%A0+N%E1%BB%99i,+Vi%E1%BB%87t+Nam&amp;t=m&amp;ll=21.002792,105.847692&amp;spn=0.024039,0.025663&amp;z=14">Xem Bản đồ cỡ lớn hơn</a></small>
      </div>
      <hr>
      <div class="slide-box">
        <span class="box-title">RECOMMENDED STORES</span>
        <div class="box-content">
          <ul class="recommended-items">
            <li>
              <img src="http://i.place.vn/Content/images/places/86/sen-tay-ho-1_small.jpg">
              <div class="item-info">
                <span class="item-title"><a href="#">Nhà hàng Sen Tây Hồ</a></span>
                <p class="item-address">
                  614 Lạc Long Quân (khuôn viên Công viên nước Hồ Tây) - Tây Hồ - Hà Nội
                </p>
              </div>
            </li>
            <li>
              <img src="http://i.place.vn/Content/images/places/92/sen%20ha%20thanh_small.jpg">
              <div class="item-info">
                <span class="item-title"><a href="#">Nhà hàng Sen Hà Thành</a></span>
                <p class="item-address">
                  177 Bùi Thị Xuân (sau tòa nhà Vincom) - Hai Bà Trưng - Hà Nội
                </p>
              </div>
            </li>
            <li>
              <img src="http://i.place.vn/Content/images/places/292/sumo-bbq-2_small.jpg">
              <div class="item-info">
                <span class="item-title"><a href="#">SumoBBQ - Hoàng Quốc Việt</a></span>
                <p class="item-address">
                  132 – 134 Hoàng Quốc Việt - Cầu Giấy - Hà Nội
                </p>
              </div>
            </li>
            <li>
              <img src="http://i.place.vn/Content/images/places/66308/539678-325794627511459-78467733-n_small.jpg">
              <div class="item-info">
                <span class="item-title"><a href="#">Outdoor Club</a></span>
                <p class="item-address">
                  Ngõ 200 Âu Cơ - Tây Hồ - Hà Nội
                </p>
              </div>
            </li>
            <li>
              <img src="http://i.place.vn/Content/images/places/86/sen-tay-ho-1_small.jpg">
              <div class="item-info">
                <span class="item-title"><a href="#">Công ty Cổ phần Bán lẻ Kỹ thuật số FPT</a></span>
                <p class="item-address">
                  614 Lạc Long Quân (khuôn viên Công viên nước Hồ Tây) - Tây Hồ - Hà Nội
                </p>
              </div>
            </li>
            <li>
              <img src="http://i.place.vn/Content/images/places/21950/sac-phong-nhan-vien_small.jpg">
              <div class="item-info">
                <span class="item-title"><a href="#">Nhà hàng 1946 - Mai Anh Tuấn</a></span>
                <p class="item-address">
                  Biệt thự số 50 phố Mai Anh Tuấn - bờ hồ Hoàng Cầu - Đống Đa - Hà Nội
                </p>
              </div>
            </li>
          </ul>
        </div>
      </div>
      Comment review dat o dau. Hay la dat sang mot tab moi
      
    </div>
  </div>
  <div id="footer"></div>
</div>
<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>