config/routes.rb
AppsContest::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :promotions
  resources :categories
  resources :stores
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root "maps#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/signin', to: 'sessions#new'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :category
  belongs_to :store

  validates :description, presence: true
  validate :valid_dates

  before_save :convert_tags_to_id

  def convert_tags_to_string
    s = self.tags
    if self.tags
      self.tags.split(",").each do |tag_id|
        s = s.gsub(tag_id, Tag.find(tag_id.to_i).name)
      end
    end
    s
  end

  private
  def valid_dates
    if begin_date >= end_date
      self.errors.add :begin_date, ' has to be after end date'
    end
  end
  def convert_tags_to_id
    s = self.tags
    self.tags.split(",").each do |tag_name|
      if Tag.find_by(name: tag_name)
        s = s.gsub(tag_name, Tag.find_by(name: tag_name).id.to_s)
      else
        s = s.gsub(tag_name, Tag.create(name: tag_name).id.to_s)
      end
    end
    self.tags = s
  end

end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]
  before_action :convert_tags, only: [:edit]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)
    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @promotion }
      else
        format.html { render action: 'new' }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    def convert_tags
      @promotion.tags = @promotion.convert_tags_to_string
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:begin_date, :end_date, :description, :status, :store_id, :category_id, :tags )
    end

end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <script>
    jQuery(document).ready(function() {
    jQuery('.datepicker').datepicker({
        dateFormat : 'yy-mm-dd',
        minDate   : 0
      });
    });
  </script>
  <div class="field">
    <%= f.label :begin_date %><br>
    <%= f.text_field :begin_date, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select(:status,"pending" => "pending", "public" => "public" , "banned" => "banned") %>
  </div>
  <div class="field">
    <%= f.label :Store %><br>
    <%= f.collection_select(:store_id, Store.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :Category %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing promotion</h1>

<%= render 'form' %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<h1>Listing promotions</h1>

<table>
  <thead>
    <tr>
      <th>Begin date</th>
      <th>End date</th>
      <th>Description</th>
      <th>Status</th>
      <th>Store</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= promotion.begin_date.to_date %></td>
        <td><%= promotion.end_date.to_date%></td>
        <td><%= promotion.description %></td>
        <td><%= promotion.status %></td>
        <td><%= promotion.store.try(:name) %></td>
        <td><%= promotion.category.try(:name) %></td>
        <td><%= link_to 'Show', promotion %></td>
        <td><%= link_to 'Edit', edit_promotion_path(promotion) %></td>
        <td><%= link_to 'Destroy', promotion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promotion', new_promotion_path %>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render 'form' %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Begin date:</strong>
  <%= @promotion.begin_date.to_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @promotion.end_date.to_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @promotion.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @promotion.status %>
</p>

<p>
  <strong>Store:</strong>
  <%= @promotion.store.try(:name) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @promotion.category.try(:name) %>
</p>
<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>